# Elixir CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-elixir/ for more details
version: 2.1

commands:
  fetch_deps:
    description: "Fetch deps, build, and cache them"
    steps:
      - restore_cache:
          keys:
            - deps-v1-{{ .Branch }}-{{ .Revision }}
            - deps-v1-{{ .Branch }}-
            - deps-v1-
      - run: mix do local.hex --force, local.rebar --force
      - run: mix do deps.get, deps.compile
      - save_cache:
          key: deps-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - "deps"
            - "_build"

jobs:
  test:
    docker:
      - image: elixir:1.7
    working_directory: ~/repo
    steps:
      - checkout
      - fetch_deps

      - run: mkdir -p reports/exunit
      - run: mix coveralls.json
      - run: bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: reports

  dialyzer:
    docker:
      - image: elixir:1.7
    working_directory: ~/repo
    steps:
      - checkout
      - fetch_deps

      - restore_cache:
          keys:
            - dialyzer-v1-{{ checksum "mix.lock" }}
            - dialyzer-v1
      - run: mix dialyzer --plt
      - save_cache:
          key: dialyzer-v1-{{ checksum "mix.lock" }}
          paths:
            - "_build"
      - run: mix dialyzer --halt-exit-status

  format:
    docker:
      - image: elixir:1.7
    working_directory: ~/repo
    steps:
      - checkout
      - fetch_deps
      - run: mix format --check-formatted

workflows:
  version: 2
  testing:
    jobs:
      - test
      - dialyzer
      - format
